spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: qqq
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  thymeleaf:
    encoding: utf-8
  jackson:
    serialization:
      indent-output: true
server:
  port: 8189
  servlet:
    context-path: /market
    session:
      timeout: 60s